### PR TITLE
version 6.2.1

### PR DESCRIPTION
**Pull request by ReimarBauer**
Hi @robcresswell 

I need an update, because of utf-8 problems.

please review and maybe create a new pypi package.

greetings
Reimar

### CODE REVIEW

**Comment by robcresswell** [comment]
@ReimarBauer I'm not really sure why you're tagging me, I've not worked on OpenStack for about 5 years now 😃 I believe you need https://wiki.openstack.org/wiki/How_To_Contribute

**Comment by robcresswell** [comment]
As it happens, the 300,000 line change is too large for me to open to help anyway

**Comment by ReimarBauer** [comment]
I expected that this was the source for the pypi package you maintain ;)
https://pypi.org/project/XStatic-Font-Awesome/


If you add me as co-maintainer for the pypi package I can update it there too.

**Comment by robcresswell** [comment]
@ReimarBauer There are multiple maintainers; you need to go via the OpenStack contribution process

**Comment by ReimarBauer** [comment]
closing this here, I got maintainer for this package too

**Comment by robcresswell** [comment]
@ReimarBauer Er, how? This feels really shady. IIRC the package was managed by openstackci and the openstack contribution process

**Comment by ReimarBauer** [comment]
The package orgin was MoinMoin. And openstack got co-maintainer. I am also belong to the MoinMoin project and we use  it there still for moin-2 development.

A package can have more than one maintainer.

**Comment by ReimarBauer** [comment]
I am willing to look on the contribution guidelines of this project. But I am not using XStatic because it is used by openstack.

**Pull request closed without merging**
